"""remove username

Revision ID: 35d970d0ac03
Revises: 1286f26acc11
Create Date: 2013-04-01 18:14:08.222455

"""

# revision identifiers, used by Alembic.
revision = '35d970d0ac03'
down_revision = '1286f26acc11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('user', u'username')
    # nasty hack because sqlite doesn't support drop column :(
    #op.execute("BEGIN TRANSACTION")
    op.execute("CREATE TEMPORARY TABLE users_backup(id,pw_hash,email,created_date)")
    op.execute("INSERT INTO users_backup SELECT id,pw_hash,email,created_date FROM user")
    op.execute("DROP TABLE user")
    op.execute("CREATE TABLE user (id INTEGER NOT NULL, pw_hash VARCHAR(255), email VARCHAR(120), created_date DATETIME, PRIMARY KEY (id), UNIQUE (email))")
    op.execute("INSERT INTO user SELECT id,pw_hash,email,created_date FROM users_backup")
    op.execute("DROP TABLE users_backup")
    #op.execute("COMMIT")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'username', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
